= Anypoint Object Store 2
:keywords: Object Store 2, object store

Anypoint Object Store 2 builds on the Mule Object Store and extends it as a true platform object store that can be used for caching and sharing data across applications.

A person or an application can create as many object stores as needed to store different kinds of data. For example, an application can use Object Store 2 to create an API cache, an link:/mule-user-guide/v/3.8/idempotent-filter[idempotent filter], or a way to store information to share between Mule workers, such as OAuth tokens. All of these would be different object stores that can be shared across applications.

== Features

Object Store 2 provides these features:

* Content storage between applications
* REST API for creating and managing object stores
* Anypoint Studio connector
* Rate limiting across applications
* API caching
* Distributed memory cacheing
* Mule reliability components: IdempotentRouter, UntilSuccessful, and Resequencer
* Node.js microservices

== Documents

The Object Store 2 documentation set consists of:

* link:/anypoint-mq/os2-tutorial[Tutorial]
* Workflow Guide
* Security Guide
* Operations Guide
* Connector Guide
* REST APIs
* FAQ
* Release Notes

== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
